import { ImageEditor, IMAGE_FORMAT } from './image-editor.js';
const REPO='Blinytz/memo-web', BRANCH='main', API=`https://api.github.com/repos/${REPO}`;
const token=()=>sessionStorage.getItem('memoGithubToken')||'';
const githubHeaders=()=>({'Authorization':`Bearer ${token()}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'});
const $=s=>document.querySelector(s), state={data:null,listId:null,entryId:null,selected:new Set(),undo:[],redo:[],dirty:false,pendingDiff:null,manifest:null};
const statuses=['manquante','importee','a_cadrer','a_verifier','validee','verrouillee','source_cassee','conflit'];
let editor;
async function load(){try{state.data=await (await fetch(`data/atelier/workspace.json?t=${Date.now()}`,{cache:'no-store'})).json();state.listId=state.data.lists.find(l=>!l.deletedAt)?.id;if(!$('#f-status').options.length)statuses.forEach(s=>$('#f-status').add(new Option(s.replaceAll('_',' '),s)));render();status(token()?'enregistré · GitHub connecté':'lecture seule · connecter GitHub')}catch(e){console.error(e);status('erreur de chargement');alert('Impossible de charger les données Mémo. Rechargez la page.')}}
function status(s){$('#status').textContent=s}
function snapshot(){state.undo.push(JSON.stringify(state.data));if(state.undo.length>40)state.undo.shift();state.redo=[]}
function change(fn){snapshot();fn();state.dirty=true;status('modifications en cours');render()}
function currentList(){return state.data.lists.find(l=>l.id===state.listId)}
function entries(){return state.data.entries.filter(e=>e.listId===state.listId&&!e.deletedAt)}
function render(){renderNav();renderTable();renderDetail()}
function renderNav(){const q=$('#search').value.toLowerCase();$('#nav').innerHTML=state.data.categories.filter(c=>!c.deletedAt).sort((a,b)=>a.order-b.order).map(c=>`<div class="category">${esc(c.name)}</div>${state.data.lists.filter(l=>l.categoryId===c.id&&!l.deletedAt&&(!q||l.name.toLowerCase().includes(q)||state.data.entries.some(e=>e.listId===l.id&&e.name.toLowerCase().includes(q)))).sort((a,b)=>a.order-b.order).map(l=>`<button class="list ${l.id===state.listId?'active':''}" data-list="${l.id}">${esc(l.icon)} ${esc(l.name)} <small>(${state.data.entries.filter(e=>e.listId===l.id&&!e.deletedAt).length})</small></button>`).join('')}`).join('')}
function renderTable(){const list=currentList();if(!list)return;$('#list-title').textContent=list.name;const es=entries().filter(e=>!$('#search').value||JSON.stringify(e).toLowerCase().includes($('#search').value.toLowerCase()));const missing=es.filter(e=>['manquante','source_cassee','conflit'].includes(e.image?.status)).length;$('#metrics').textContent=`${es.length} entrées · ${missing} image(s) à traiter`;$('#thead').innerHTML=`<tr><th>✓</th><th>N°</th><th>Image</th><th>Nom</th>${list.columns.slice(2).map(c=>`<th>${esc(c)}</th>`).join('')}</tr>`;$('#tbody').innerHTML=es.sort((a,b)=>a.order-b.order).map(e=>`<tr data-entry="${e.id}" class="${state.selected.has(e.id)?'selected':''}"><td><input type="checkbox" ${state.selected.has(e.id)?'checked':''}></td><td contenteditable data-field="number">${esc(e.number)}</td><td>${e.image?.thumb?`<img loading="lazy" src="/${esc(e.image.thumb)}">`:'—'}</td><td contenteditable data-field="name">${esc(e.name)}</td>${list.columns.slice(2).map(c=>`<td contenteditable data-extra="${esc(c)}">${esc(e.fields?.[c]||'')}</td>`).join('')}</tr>`).join('')}
function renderDetail(){const e=state.data.entries.find(x=>x.id===state.entryId);$('#empty').hidden=!!e;$('#form').hidden=!e;if(!e)return;for(const [id,key] of [['f-id','id'],['f-number','number'],['f-name','name'],['f-title','title'],['f-subtitle','subtitle'],['f-description','description'],['f-extra','extraText'],['f-wiki','wikipedia']])$(id.startsWith('#')?id:'#'+id).value=e[key]||'';$('#f-status').value=e.image?.status||'manquante';$('#f-locked').checked=!!e.image?.locked;$('#open-wiki').href=e.wikipedia||'#';$('#dynamic-fields').innerHTML=Object.entries(e.fields||{}).map(([k,v])=>`<label>${esc(k)}<input data-dynamic="${esc(k)}" value="${esc(v)}"></label>`).join('')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function githubCommit(files,message){if(!token()){status('connexion GitHub requise');$('#github-dialog').showModal();throw new Error('Jeton GitHub requis')}const ref=await fetch(`${API}/git/ref/heads/${BRANCH}`,{headers:githubHeaders(),cache:'no-store'});if(!ref.ok)throw new Error(`Connexion GitHub refusée (${ref.status})`);const parent=(await ref.json()).object.sha;const commit=await (await fetch(`${API}/git/commits/${parent}`,{headers:githubHeaders()})).json();const tree=[];for(const f of files){const r=await fetch(`${API}/git/blobs`,{method:'POST',headers:{...githubHeaders(),'Content-Type':'application/json'},body:JSON.stringify({content:f.base64||btoa(unescape(encodeURIComponent(f.text))),encoding:'base64'})});if(!r.ok)throw new Error(`Échec du fichier ${f.path}`);tree.push({path:f.path,mode:'100644',type:'blob',sha:(await r.json()).sha})}const tr=await fetch(`${API}/git/trees`,{method:'POST',headers:{...githubHeaders(),'Content-Type':'application/json'},body:JSON.stringify({base_tree:commit.tree.sha,tree})});if(!tr.ok)throw new Error('Échec de préparation du commit');const cr=await fetch(`${API}/git/commits`,{method:'POST',headers:{...githubHeaders(),'Content-Type':'application/json'},body:JSON.stringify({message,tree:(await tr.json()).sha,parents:[parent]})});if(!cr.ok)throw new Error('Échec de création du commit');const next=(await cr.json()).sha;const ur=await fetch(`${API}/git/refs/heads/${BRANCH}`,{method:'PATCH',headers:{...githubHeaders(),'Content-Type':'application/json'},body:JSON.stringify({sha:next,force:false})});if(!ur.ok)throw new Error('Conflit : rechargez la page avant de réessayer');return next}
async function save(){try{state.data.revision=Number(state.data.revision||0)+1;state.data.updatedAt=new Date().toISOString();await githubCommit([{path:'data/atelier/workspace.json',text:JSON.stringify(state.data,null,2)+'\n'}],'Atelier Mémo : mise à jour des données');state.dirty=false;status('enregistré sur GitHub')}catch(e){state.data.revision=Math.max(1,state.data.revision-1);status('erreur');alert(e.message)}}
$('#nav').onclick=e=>{const id=e.target.closest('[data-list]')?.dataset.list;if(id){state.listId=id;state.entryId=null;state.selected.clear();$('aside').classList.remove('mobile-open');render()}};
$('#mobile-menu').onclick=()=>$('aside').classList.add('mobile-open');$('#close-nav').onclick=()=>$('aside').classList.remove('mobile-open');
$('#tbody').onclick=e=>{const tr=e.target.closest('tr');if(!tr)return;const id=tr.dataset.entry;if(e.target.type==='checkbox'){e.target.checked?state.selected.add(id):state.selected.delete(id)}else state.entryId=id;render()};
$('#tbody').oninput=e=>{const tr=e.target.closest('tr'),entry=state.data.entries.find(x=>x.id===tr?.dataset.entry);if(!entry)return;if(!state.dirty)snapshot();if(e.target.dataset.field)entry[e.target.dataset.field]=e.target.textContent;if(e.target.dataset.extra)entry.fields[e.target.dataset.extra]=e.target.textContent;state.dirty=true;status('modifications en cours')};
$('#search').oninput=render;$('#save').onclick=save;window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
for(const [id,key] of [['f-number','number'],['f-name','name'],['f-title','title'],['f-subtitle','subtitle'],['f-description','description'],['f-extra','extraText'],['f-wiki','wikipedia']])$('#'+id).oninput=e=>{const entry=state.data.entries.find(x=>x.id===state.entryId);if(!state.dirty)snapshot();entry[key]=e.target.value;state.dirty=true;status('modifications en cours');if(key==='wikipedia')$('#open-wiki').href=e.target.value};
$('#dynamic-fields').oninput=e=>{const entry=state.data.entries.find(x=>x.id===state.entryId);entry.fields[e.target.dataset.dynamic]=e.target.value;state.dirty=true;status('modifications en cours')};$('#f-status').onchange=e=>change(()=>state.data.entries.find(x=>x.id===state.entryId).image.status=e.target.value);$('#f-locked').onchange=e=>change(()=>state.data.entries.find(x=>x.id===state.entryId).image.locked=e.target.checked);
$('#add-category').onclick=()=>{const name=prompt('Nom de la catégorie');if(name)change(()=>state.data.categories.push({id:crypto.randomUUID(),name,order:state.data.categories.length,deletedAt:null}))};$('#add-list').onclick=()=>{const name=prompt('Nom de la liste'),cat=state.data.categories.find(c=>!c.deletedAt);if(name&&cat)change(()=>{const l={id:crypto.randomUUID(),name,icon:'📚',categoryId:cat.id,columns:['Numéro','Image','Nom'],order:state.data.lists.length,metadata:{},deletedAt:null};state.data.lists.push(l);state.listId=l.id})};
$('#add-row').onclick=()=>change(()=>{const list=currentList(),e={id:crypto.randomUUID(),listId:list.id,number:String(entries().length+1),name:'Nouvelle entrée',title:'Nouvelle entrée',subtitle:'',description:'',extraText:'',wikipedia:'',fields:{},order:entries().length,deletedAt:null,externalIds:{},image:{source:null,full:null,thumb:null,crop:{cx:.5,cy:.5,w:1},status:'manquante',locked:false,provenance:{}}};state.data.entries.push(e);state.entryId=e.id});
$('#duplicate-row').onclick=()=>{const src=state.data.entries.find(e=>state.selected.has(e.id)||e.id===state.entryId);if(src)change(()=>state.data.entries.push({...structuredClone(src),id:crypto.randomUUID(),number:String(Number(src.number||0)+1),order:entries().length,image:{...src.image,locked:false}}))};$('#trash-row').onclick=()=>{if(!confirm('Placer la sélection dans la corbeille ?'))return;change(()=>state.data.entries.filter(e=>state.selected.has(e.id)||(state.selected.size===0&&e.id===state.entryId)).forEach(e=>{e.deletedAt=new Date().toISOString();state.data.trash.push({type:'entry',id:e.id,at:e.deletedAt})}))};
$('#renumber').onclick=()=>{const start=Number(prompt('Premier numéro',1));if(!start)return;const targets=state.selected.size?entries().filter(e=>state.selected.has(e.id)):entries();state.pendingDiff=targets.map((e,i)=>({id:e.id,field:'number',before:e.number,after:String(start+i)}));showDiff()};function showDiff(){$('#diff-content').innerHTML=state.pendingDiff.map(d=>`<div class="diff-row"><b>${esc(d.id.slice(0,12))}</b><span>${esc(d.before)}</span><b>→</b><span>${esc(d.after)}</span></div>`).join('');$('#diff-dialog').showModal()}$('#diff-apply').onclick=()=>change(()=>{for(const d of state.pendingDiff){const e=state.data.entries.find(x=>x.id===d.id);e[d.field]=d.after}state.pendingDiff=null;$('#diff-dialog').close()});
$('#undo').onclick=()=>{if(!state.undo.length)return;state.redo.push(JSON.stringify(state.data));state.data=JSON.parse(state.undo.pop());state.dirty=true;render()};$('#redo').onclick=()=>{if(!state.redo.length)return;state.undo.push(JSON.stringify(state.data));state.data=JSON.parse(state.redo.pop());state.dirty=true;render()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#close-detail').onclick=()=>{$('.detail').classList.remove('mobile-open');state.entryId=null;renderDetail()};
$('#notes-view').onclick=$('#bulk-note').onclick=()=>{renderNotes();$('#notes-dialog').showModal()};function renderNotes(){$('#notes-list').innerHTML=state.data.notes.map(n=>`<div class="note"><b>${esc(n.status)} · ${esc(n.priority)}</b><p>${esc(n.text)}</p><small>${n.targets.entryIds.length} entrée(s), ${n.targets.listIds.length} liste(s)</small></div>`).join('')||'<p>Aucune note.</p>'}$('#note-add').onclick=()=>{const text=$('#note-text').value.trim();if(!text)return;change(()=>state.data.notes.push({id:crypto.randomUUID(),text,targets:{entryIds:[...state.selected],listIds:state.selected.size?[]:[state.listId]},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),status:$('#note-status').value,priority:$('#note-priority').value}));$('#note-text').value='';renderNotes()};
$('#edit-image').onclick=async()=>{const e=state.data.entries.find(x=>x.id===state.entryId);if(e.image?.locked&&!confirm('Cette image est verrouillée. La modifier ?'))return;$('#image-dialog').showModal();editor ||= new ImageEditor($('#image-frame'),$('#image-source'),$('#image-preview'));if(e.image?.source)try{await editor.load('/'+e.image.source);editor.setCrop(e.image.crop)}catch{alert('Image source illisible. Importez un nouveau fichier.')}};$('#img-file').onclick=()=>$('#img-input').click();$('#img-input').onchange=e=>loadFile(e.target.files[0]);async function loadFile(f){if(!f)return;await editor.load(URL.createObjectURL(f))}$('#image-frame').ondragover=e=>e.preventDefault();$('#image-frame').ondrop=e=>{e.preventDefault();loadFile(e.dataTransfer.files[0])};window.addEventListener('paste',e=>{if(!$('#image-dialog').open)return;const f=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(f)loadFile(f)});$('#img-fill').onclick=()=>editor.fill();$('#img-contain').onclick=()=>editor.contain();$('#img-plus').onclick=()=>editor.zoom(1.2);$('#img-minus').onclick=()=>editor.zoom(1/1.2);$('#img-undo').onclick=()=>editor.back();
const blob64=b=>new Promise((ok,no)=>{const f=new FileReader();f.onload=()=>ok(f.result.split(',')[1]);f.onerror=no;f.readAsDataURL(b)});
$('#img-save').onclick=async()=>{try{const e=state.data.entries.find(x=>x.id===state.entryId),out=await editor.exports(),base=`assets/atelier/${e.id}`;e.image.source=`${base}/original.webp`;e.image.full=`${base}/full.webp`;e.image.thumb=`${base}/thumb.webp`;e.image.crop=editor.crop();e.image.status='importee';e.image.provenance={kind:'manual',at:new Date().toISOString()};state.data.revision=Number(state.data.revision||0)+1;state.data.updatedAt=new Date().toISOString();await githubCommit([{path:`${base}/original.webp`,base64:await blob64(out.original)},{path:`${base}/full.webp`,base64:await blob64(out.full)},{path:`${base}/thumb.webp`,base64:await blob64(out.thumb)},{path:'data/atelier/workspace.json',text:JSON.stringify(state.data,null,2)+'\n'}],`Atelier Mémo : image ${e.name}`);state.dirty=false;status('image enregistrée sur GitHub');$('#image-dialog').close();render()}catch(e){status('erreur');alert(e.message)}};
$('#import-wiki').onclick=()=>$('#import-dialog').showModal();$('#manifest-input').onchange=async e=>{state.manifest=JSON.parse(await e.target.files[0].text());const r=await fetch('/api/wikideck/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state.manifest)}),report=await r.json();state.importReport=report;const count=k=>report.matches.filter(m=>m.status===k).length;$('#import-report').innerHTML=`<p><b>Analyse sans écriture</b></p><span class="badge">${count('certain')} certaines</span><span class="badge">${count('probable')} probables</span><span class="badge">${count('ambiguous')} ambiguës</span><span class="badge">${count('wikideck_only')} absentes de Mémo</span><p>Les images verrouillées ne seront jamais remplacées sans décision explicite. Les ambiguïtés et cartes absentes sont laissées pour décision manuelle.</p>`;$('#import-apply').hidden=false};
$('#import-apply').onclick=async()=>{if(!confirm('Appliquer uniquement les correspondances non ambiguës affichées ?'))return;const decisions=state.importReport.matches.filter(m=>['certain','probable'].includes(m.status)&&m.candidates.length===1).map(m=>({cardId:m.card.id,entryId:m.candidates[0].id}));const r=await fetch('/api/wikideck/apply',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...state.manifest,confirm:true,decisions})}),j=await r.json();if(!r.ok)return alert(j.error||j.errors?.join('\n'));$('#import-report').innerHTML+=`<p><b>${j.results.filter(x=>x.status==='imported').length} image(s) importée(s).</b> ${j.results.filter(x=>x.status==='conflict').length} conflit(s) préservé(s).</p>`;await load()};
setInterval(()=>{if(state.dirty)save()},30000);load();
$('#github-settings').onclick=()=>{$('#github-token').value=token();$('#github-dialog').showModal()};$('#github-connect').onclick=async()=>{const value=$('#github-token').value.trim();sessionStorage.setItem('memoGithubToken',value);const r=await fetch(`${API}`,{headers:githubHeaders()});if(!r.ok){sessionStorage.removeItem('memoGithubToken');return alert('Jeton refusé ou accès insuffisant.')}$('#github-dialog').close();status('enregistré · GitHub connecté')};
